<?php

/* 
 * 1) get child menu items from current page
 * 2) iterate through each item and:
 *  a) pull node id from item
 *  b) get title, teaser image, summary text, link from each item
 *  c) display each item
 * 3) done!
 * 
 */

// create block
// Implements hook_block_info().
function menu_children_block_block_info() {
  $blocks['menu_children_block'] = array(
    // info: The name of the block.
    'info' => t('Menu Children Block'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
    'region' => 'content',
  );
  return $blocks;
}


// get child menu items
/* display menu title in block */
// Implements hook_block_view().
function menu_children_block_block_view($delta = '') {
    switch($delta) {
        case "menu_children_block" :
            // get menu info from current page and then get all children
            $parent = menu_link_get_preferred($_GET['q']);
            $parameters = array(
              'active_trail' => array($parent['plid']),
              'only_active_trail' => FALSE,
              'min_depth' => $parent['depth']+1,
              'max_depth' => $parent['depth']+1,
              'conditions' => array('plid' => $parent['mlid']),
            );
            $children = menu_build_tree($parent['menu_name'], $parameters); // get menu tree of children of main menu item
            $node_ids = Array();
            $output = '';
            // iterate through each menu item, get link path and then add to array 
            if ($children) {
                $output = get_menu_child_entities($children);
            }
            $block['subject'] = t('');
            $block['content'] = $output;
            break;
    }
    return $block;
}

function get_menu_child_entities($children) {
    foreach ($children as $child) { // get the link path 
        $strpath = $child['link']['link_path'];
        $entity_links[] = $strpath;
    }
    // get all nodes from menu items
    if ($entity_links) {
        $count = 0; $output = '';
        foreach ($entity_links as $entity_item) {
            $entity_id = substr($entity_item, strrpos($entity_item, '/')+1);
            $count++;
            $odd_even = $count % 2 == 0 ? 'even' : 'odd';
            if (strpos($entity_item, 'node') > -1) { // if not a term then a node
                $output .= get_node_fields($entity_id,$count,$odd_even);
            }
            else if (strpos($entity_item, 'term') > -1) {  // else a term
                $output .= get_term_fields($entity_id,$count,$odd_even);                            
            }
            //dsm(strpos($entity_item, 'node'));
        }
    }
    return $output;
}

function get_node_fields($entity_id,$count,$odd_even) {
    $output = '';
    $node_fields = entity_load('node', array($entity_id));
    $node_teaser = entity_view('node', $node_fields, 'teaser');
    /*
    $teaser_text = field_view_field('node', $node_fields[$entity_id], 'body', array('label' => 'hidden', 'type' => 'text_summary_or_trimmed'));
    //$teaser_image = field_view_field('node', $node_fields[$entity_id], 'field_teaser_image', array('label' => 'hidden'));
    $nodelink = url('node/'.$node_fields[$entity_id]->nid);
    $nodetitle = $node_fields[$entity_id]->title;
    $output .= '<div class="fields-row row-'.$count.' '.$odd_even.'"><div class="field-content field-title"><a href="'.$nodelink.'">'.$nodetitle.'</a></div>
        <div class="field-content field-summary">'.render($teaser_text).'</div></div>';
    */
    //dsm($node_fields);
    $output = render($node_teaser);
    return $output;
}

function get_term_fields($entity_id,$count,$odd_even) {
    $output = '';
    $term_fields = entity_load('taxonomy_term', array($entity_id));
    $term_teaser = entity_view('taxonomy_term', $term_fields, 'token');
    //dsm($term_fields);
    /*
    $nodelink = url('taxonomy/term/'.$term_fields[$entity_id]->tid);
    $nodetitle = $term_fields[$entity_id]->name;
    $teaser_text = field_view_field('taxonomy_term', $term_fields[$entity_id], 'field_teaser_text', array('label' => 'hidden'));
    $output .= '<div class="fields-row row-'.$count.' '.$odd_even.'"><div class="field-content field-title"><a href="'.$nodelink.'">'.$nodetitle.'</a></div>
        <div class="field-content field-summary">'.render($teaser_text).'</div></div>';
    */
    $output = render($term_teaser);
    return $output;
}